### ISSUE TITLE
Add an explicit "Greenland" designation in the compset name

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CISM-wrapper#39]
Before adding support for Antarctica, I'd like to lay the groundwork for having an explicit designator in the compset describing whether you're running with Greenland, Antarctica, both Greenland and Antarctica, or some other ice sheet(s). The first step will be adding explicit designation for Greenland.

I plan to do this in a backwards-compatible way, so the lack of explicit designation will be equivalent to specifying Greenland-only.

**Comment by billsacks** [comment]
For compset aliases I'm thinking something like:

- `T1850Gg` -> Greenland only
- `T1850Ga` -> Antarctica only
- `T1850Gga` -> Greenland & Antarctica

etc.

@whlipscomb @gunterl @Katetc thoughts on that?

**Comment by billsacks** [comment]
Maybe `T1850Gag` rather than `T1850Gga`. The general rule would be: if multiple ice sheets, they appear in alphabetical order.

**Comment by whlipscomb** [comment]
@billsacks - This makes sense to me.  Down the road, other potential ice sheets could be 'n' for Northern Hemisphere, or maybe 'l' for Laurentide and 'e' for Eurasian.
