### ISSUE TITLE
Remove remnants of scripts to generate default i/o files

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CISM-wrapper#47]
@Katetc You changed the CISM build a while ago so that the i/o files are generated as part of the build process, right? I noticed that case directories still have `Buildconf/cismIOconf`, which contains the old scripts that users could use to regenerate these files manually. I'm thinking that this should be removed, and along with it, removing the relevant files from the source tree, which include `bld/cismIO/cism.buildIO.template.csh`, `cime_config/cism.template`, and maybe others. Do you agree?

**Comment by Katetc** [comment]
Yes, I added code to generate those files as part of the build. I thought I did remove the files that are no longer needed, but if you find some still hanging around, then please remove them as part of your cleanup.

**Comment by billsacks** [comment]
Sorry, I'm dealing with too many threads already right now, which is why I opened this issue rather than just figuring out what needs to be removed. This was turning into a peeling onion.

**Comment by billsacks** [comment]
Actually, after a couple more minutes of looking, it may not be so bad, so I can take a stab at this. However, I see that cism.template is still invoked from cime, so I would need to leave something in place for a little while, until cime has been updated to no longer expect this. I'll put this in an upcoming cime PR.

I'm a little confused because in https://github.com/ESCOMP/CISM-wrapper/issues/18#issuecomment-419281858 you said you had already done this, so I'm not sure why these files are still here.

**Comment by billsacks** [comment]
Hmmm, it looks like you never made any changes to the CISM-wrapper code in #22 - only to the source_cism version. I think this will be easy enough, so I'll take it on.
