### ISSUE TITLE
PTS_MODE doesn't work with cism

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/cism-wrapper#7]
I think this is a WONTFIX. But, one of the students today tried to do a PTS_MODE case with a compset that included cism. It tried to do something, but she showed me an output file that looked like greenland. So it's obviously not doing the right thing. So I want to document this as something that you can't do.

**Comment by billsacks** [comment]
Right, this is a wontfix: it doesn't make sense to try to do a single-point simulation with a dynamic ice sheet model.
